### ISSUE TITLE
(DuckieTV) Add nightly only if its different from last release

### ISSUE THREAD

**Issue by majkinetor** [JourneyOver/chocolatey-packages#19]
It doesn't make any sence to do this IMO. I would be happier if cup --pre works only when there is actuall update.

You could compare the hash of the last commit (perhaps in release notes) from the current one and push only when they differ. That would be much better, don't you think ?

**Comment by JourneyOver** [comment]
Probably would be better, I'm sure Choco devs would be happier for sure xD I'll look into this when I get my computer back from repair shop (will be sometime this week) as I have several packages that I need to fix.

**Comment by JourneyOver** [comment]
Might take a bit longer to get this implemented, got my computer back but have to take it back to repair shop again because they failed to actually fix much..

**Comment by JourneyOver** [comment]
@majkinetor before I even push this to master branch, would this here work? https://github.com/JourneyOver/chocolatey-packages/blob/duckienightlyfix/automatic/duckietv_pre/update.ps1#L38-L47

Pretty much pulling the body which ends up looking something like - `DuckieTV nightly release for Fri Dec 21 2018 01:56:20.\n**Changelog:**\n - dcb74e2 eztv: new domain .io` for example, but I'm regexing it down to only include this ` - dcb74e2` bit, and putting it into a .txt file. Upon next release and AU going to do it's thing, it checks the body again for the regexed bit, and then does a check against the old one in the .txt file. If they match it does `

```
  if ($hashold -eq $hashnew) {
    Write-Host 'Changelog hash matches old release'
    return 'ignore'
  }
```

which if what I'm hoping happens, makes it ignore the update? but if it doesn't match then it continues on with the update?

Obviously switching out the old hash for the new in the .txt file after the above check so it doesn't mess things up xD

**Comment by majkinetor** [comment]
That should work locally but will fail on AV as txt file is lost. You will have to add this file to git repo I think for this to work or record your hashsum in the nuspec file since it will be saved to git on update.

**Comment by JourneyOver** [comment]
@majkinetor actually I might need to disable nightlies completely or something, as just trying to even push up a release for the nightly package results in an error 

```
Attempting to push duckietv.2018.1222.0130-nightly.nupkg to https://push.chocolatey.org There was an internal server error, which might mean the package already exists on a Simple OData Server.
```

which has been going on since at least the 14th of November (which is one reason why I disabled nightlies until further notice beforehand hoping the issue would be fixed by the time that I got my computer situation taken care of). So far this has been the only package though that has resulted in this error and I really don't understand the error any.

**Comment by majkinetor** [comment]
That is upstream bug it seems massive since it happens to many. 

/cc @ferventcoder @gep13

⁣Sent from BlueMail ​

**Comment by JourneyOver** [comment]
Ah got it, thanks for ccing them as well, hopefully they can fix the issue.

**Comment by gep13** [comment]
@JourneyOver as @majkinetor mentioned, this is a known issue, which only seems to happen with embedded packages, which are larger than normal packages.

**Comment by JourneyOver** [comment]
@gep13 ah well, tbh I had been thinking about deprecating duckietv & duckietv nightly for a long time now and putting it up for someone else to possibly take care of, as I've always had issues with the package being pushed up correctly to begin with for a long time now anyways.. So maybe it's just time to go about doing it.

**Comment by JourneyOver** [comment]
So I've kinda reverted back my deprecation of duckietv and duckietv nightly.. 

First thing I did was switch stuff up a bit so it's now streamed instead of being two seperate things (since I actually took the time today to figure out how streams work a bit more)

Second thing I did was instead of having things be embedded I switched it back to being non-embedded due to the fact of how big the package has gotten in the recent months so pushing to chocolatey should be a bit smoother now.

and then the third and last thing I did was set it up so that the nightly packages are not being pushed for every single nightly release, but instead only pushing a new nightly package only when there is actual changes to the nightly (aka the point of what this issue was wanting in the first place).

Now I dunno if I did the third thing correctly or not yet, as I just recently set this all back up again, so I'm going to be watching and waiting to see if things work like they should.. but here is hoping!

if things work out then I will be closing https://github.com/chocolatey/chocolatey-package-requests/issues/500 as I will go back to just maintaining it myself (especially since it seems no one else wants to actually take up maintaining the package anyways)

If there is anything that could be done better please let me know.

**Comment by gep13** [comment]
@JourneyOver great work!  Thanks for following up with this!

**Comment by JourneyOver** [comment]
@gep13 	not a problem at all :)

and just to note as well on something, the first package with these changes that I pushed up ended up failing in the automated testing phase due to a little missed detail that I noticed (ended up leaving a `Get-AppInstallLocation` thing in forgetting it was only available with `chocolatey-core.extension` which I had taken out of the dependencies for duckietv) after it was already exempted (can no longer push up the same version to fix it now) but it will be fixed in any future versions.

Also can you please throw up a `This package skips automatic verification` thing on https://chocolatey.org/packages/sonarr if you could ^^ .. as moving forward it's going to be requiring .net 4.6.1 (and current phantom releases are failing in the automated verification due to this (already has the dependency set, but the automated verification does not like .net stuff due to it needing a restart after install xD))

**Comment by gep13** [comment]
@JourneyOver can I ask that you make that request via the package moderation page?  That way it won't get missed.

**Comment by majkinetor** [comment]
@gep13 
>  which are larger than normal packages.

Embedded packages are normal packages. Its recommended by @ferventcoder and I think you guys should work it up so that those are first class citizens.

I know that I will now get the numbers such as Gallery is only 5% or so packages in the wild, but that is missleading, Gallery is #-1 by usage/bandwith/promotional-capabilities.

> , the first package with these changes that I pushed up ended up failing in the automated testing phase due to a little missed detail that I noticed 

FYI, in case you didn't notice, you can push the same version again using `[AU pkg:ver]` sintax.

> I actually took the time today to figure out how streams work a bit more

Good choice, its easier for everybody.

Thx for the work. 

BTW, if nobody else wants it and you get tired of maintaining this again, I will accept migration to my [own repository](https://github.com/majkinetor/au-packages) since I use duckieTv daily (because of you).

**Comment by JourneyOver** [comment]
> @JourneyOver can I ask that you make that request via the package moderation page? That way it won't get missed.

@gep13 I've done that on the package versions already since the first release of needing said .net which was 2 days ago, I've even gone the route of throwing out a contact site admins thing on said package as well and nothing has happened yet, which is one reason why I asked here as well since you had recently commented xD I think one reason why the package is not getting any attention really from admins is due to the fact that it's already exempted/already set as an trusted package so it kinda bypasses admin verification processes.

-------

> FYI, in case you didn't notice, you can push the same version again using [AU pkg:ver] sintax.

@majkinetor I thought it wouldn't work if the package is already through both the `automated validation` and the `automated testing` and it gets the whole `This package is exempt from moderation` point of things (which is where I caught the mistake I made in the package was after the exemption had already been made)? 

Is that not the case anymore and we can push the same version again even after the exemption has been made if the package fails?

> Good choice, its easier for everybody.
> 
> Thx for the work.

Thanks, I've been wanting to learn how to set up the streams thing for a while now but never had the time to actually do such a thing until recently, does make things a lot easier to manage when it comes to adding in different types of releases into the packages, and it's not a problem at all :) 

> BTW, if nobody else wants it and you get tired of maintaining this again, I will accept migration to my own repository since I use duckieTv daily (because of you).

Will keep that in mind for the future, thanks ^^

**Comment by gep13** [comment]
@JourneyOver I have exempted that package from the package-verifier.

**Comment by majkinetor** [comment]
> Is that not the case anymore and we can push the same version again even after the exemption has been made if the package fails?

You can push again with the same version if it's 'waiting for maintainer' or not yet 'approved'.

**Comment by JourneyOver** [comment]
> @JourneyOver I have exempted that package from the package-verifier.

@gep13 thanks a bunch :)

---

> You can push again with the same version if it's 'waiting for maintainer' or not yet 'approved'.

@majkinetor I caught it when it was at this point here (the comment I left on the review comments thing was after it was already exempted)
![z1dbsdt](https://user-images.githubusercontent.com/13910285/51563518-3fea9300-1e52-11e9-852f-64ae1df0343a.png)
the nightly versions of the package doesn't do the whole "waiting for maintainer", "has not yet been approved" things, one it gets past the "duckietv has failed/passed automated testing" it automatically exempts itself. Which is where I think the confusion of things is coming into play here xD
