### ISSUE TITLE
Nuclear outdated

### ISSUE THREAD

**Issue by DangerMage** [JourneyOver/chocolatey-packages#60]
**Describe the bug**
The chocolatey package for nuclear isn't the most recent version

**To Reproduce**

1. Open a CMD as an admin
2. type choco install nuclear (Or if you already have it installed do choco upgrade nuclear)
3. see that it isn't the most recent version of nuclear but says that it is

**Expected behavior**
Nuclear would be the most recent version

**Screenshots**
![image](https://user-images.githubusercontent.com/57050396/153715497-c793529a-4c1f-4c13-a815-f8cffb45a7db.png)

**Computer info**
- OS: Windows 10 pro
- Chocolatey version: v0.12.1
- Package version: nuclear 0.6.17

**Chocolatey Install/Uninstall log**
https://gist.github.com/DangerMage/907b0a5f759b8ffff145088b5a16e5d1

**Additional context**
I'm not sure if you plan on having nuclear update on the new nightly build or if you are waiting for a "stable" build, just making this report because last i heard he was trying to get rid of stable vs unstable builds or something along those lines

**Comment by JourneyOver** [comment]
Yea I really prefer not to push nightlies up (unless the nightlies don't change very often) as I was doing that for duckietv a long time ago and the chocolatey devs didn't want me to do that anymore (because it was pushing a nightly well once a night) .. I'll wait a bit longer to see what the nuclear dev is going to do and then go from there.

Thanks for the report though, I'll keep an eye on things and make up my choice soonish.
