### ISSUE TITLE
Update tinymediamanager to v5

### ISSUE THREAD

**Issue by Yankees4life** [JourneyOver/chocolatey-packages#71]
Hello there

Any plans to add v5 to tmm? I don't want to manually download it if I don't have to lol

Cheers

**Comment by JourneyOver** [comment]
I have not really been keeping track of tmm much (tbh I haven't really been keeping track of any applications I have in here) since I don't use it myself so didn't even know a v5 got released xD but yea I'll look into it when I have some free time (might not be for a couple days or so). 

Did notice one thing that kind of annoys me a bit is that they changed how they package their zip file now.. V4 everything was zipped up with the files/folders and application in the root of the zip, while at least the current version of v5 everything is now in a seperate folder called "tinyMediaManager" and I'm unsure if they are going to keep things like that moving forward or if it's going to magically change in the next update. (also unsure of if they are going to continue v4 updates anymore or not)

**Comment by JourneyOver** [comment]
This has now been taken care of as of commit 67b8704f7241e1474ac4af9d257ee39ab4929b0f
