### ISSUE TITLE
[sonarr] Add a switch to install as a system tray application instead of a service

### ISSUE THREAD

**Issue by mpwhiten** [JourneyOver/chocolatey-packages#72]
This was discussed in the comment section on chocolatey a few years ago but it doesn't look like it's been implemented yet.

Would it be possible to add a switch to install as a system tray application instead of a service?

**Comment by JourneyOver** [comment]
Yeah, sorry. I've been meaning to do this at some point, but between work and various other things keeping me busy, I never fully got around to it. I'll try to look into doing this soonish, but I can't really make any promises on when exactly it'll be done, unless someone decides to randomly create a PR for this before I can get around to doing it myself.

It also doesn't help that I've kind of taken a step back from Chocolatey packages (and Chocolatey as a whole) since I barely ever use Chocolatey myself anymore. To be honest, I should probably get around to seeing if someone else will take over all my current Chocolatey packages at some point who is a bit more active.

**Comment by JourneyOver** [comment]
I have created https://github.com/chocolatey-community/chocolatey-package-requests/issues/1507 as a request for opting for a new maintainer. I am thinking about stepping away from maintaining this package (and this repository in general). I may still look into this when I get a chance if someone else hasn't taken it over beforehand.

**Comment by JourneyOver** [comment]
@mpwhiten This package has now been taken over by @mkevenaar completely, so it would be best if you could remake this issue over at https://github.com/mkevenaar/chocolatey-packages thanks :)

**Comment by mpwhiten** [comment]
@JourneyOver Will do. Thanks for your effort as maintainer on all these packages!
